### ISSUE TITLE
Error when npm i enmap-sqlite

### ISSUE THREAD

**Issue by ghost** [eslachance/enmap-sqlite#4]
![image](https://user-images.githubusercontent.com/39283132/68255348-b9cbc180-000b-11ea-99f6-a8847816080a.png)

**Comment by eslachance** [comment]
Don't install enmap-sqlite. You're using enmap 5, it doesn't use providers. 
Please refer to the installation guide for help on properly installing enmap and its dependencies. https://enmap.evie.dev/install
